name: jupyter-publish

channels:
  - conda-forge

dependencies:
  - python=3.7
  - numpy >=1.14
  - jupyterlab >=1.1.1
  - jupytext>=1.2.0rc0
  - scikit-image
  - nbdime
  - ipypublish
  - nbconvert
  - pandas
  - folium
  - matplotlib
  - scipy
  - pip
  - c-compiler
  - cxx-compiler
  - zlib
  - pip:
      - jupyterlab_latex
      - jupyterlab-git
      - nbinteract
      - jupyter-book
      - datascience
